num_units_dict:
    Input: 7
    Output: 128

activation_function_name_dict:
    Output: piecewise_linear_activation
    FF_Inh: identity_activation

weight_config_dict:
    Output:
        Input:
            dist_type: log-normal
            mean_magnitude: 0.5
            connection_type: exc

cell_tau_dict:
    Output: 0.05

synapse_tau_dict:
    Output:
        Input:
            rise: 0.001
            decay: 0.01