num_units_dict:
    Input: 7
    Output: 128
    FF_Inh: 7

activation_function_dict:
    Output:
        Name: piecewise_linear_activation
        Arguments:
            peak_output: 1.
            peak_input: 60.
            threshold: 10.
    FF_Inh:
        Name: piecewise_linear_activation
        Arguments:
            peak_output: 1.
            peak_input: 60.
            threshold: 10.

weight_config_dict:
    Output:
        Input:
            dist_type: log-normal
            mean_magnitude: 0.5
            connection_type: exc
        FF_Inh:
            dist_type: uniform
            mean_magnitude: 0.5
            connection_type: inh
    FF_Inh:
        Input:
            dist_type: uniform
            mean_magnitude: 0.2
            connection_type: exc

cell_tau_dict:
    Output: 0.05
    FF_Inh: 0.02

synapse_tau_dict:
    Output:
        Input:
            rise: 0.001
            decay: 0.01
        FF_Inh:
            rise: 0.001
            decay: 0.02
    FF_Inh:
        Input:
            rise: 0.001
            decay: 0.01


synaptic_reversal_dict:
    exc: 60.
    inh: -10.