# fraction_active_patterns_threshold = 0.6 for all populations
# fraction_active_units_threshold = 0.8 for all populations
# Sim duration = 0.35 s, activity computed as mean in range 0.15 - 0.35 s
# Weight bounds 0.01 - 3.
# Separate objective for fraction_active_units (Output population)
0:
  # Problem: patterns dropping out
  mean_weight;Output;Input: 4.437896E-02
1:
  mean_weight;Output;Input: 6.807470E-02
2:
  mean_weight;FF_Inh;Input: 1.135314E-01
  # hit new upper bound
  mean_weight;Output;FF_Inh: 2.977579E+00
  mean_weight;Output;Input: 3.404291E-01
3:
  # Problem: units dropping out
  # hit new upper bound
  mean_weight;FB_Inh;Output: 2.979531E+00
  mean_weight;Output;FB_Inh: 2.398575E-02
  mean_weight;Output;Input: 6.743321E-02
4:
  mean_weight;FB_Inh;Output: 5.248900E-02
  mean_weight;FF_Inh;Input: 1.299743E-01
  mean_weight;Output;FB_Inh: 1.048001E-02
  # hit new upper bound
  mean_weight;Output;FF_Inh: 2.997926E+00
  mean_weight;Output;Input: 3.613322E-01
5:
  mean_weight;FB_Exc;FB_Exc: 7.474511E-01
  mean_weight;FB_Exc;Output: 1.378783E-02
  mean_weight;FB_Inh;FB_Exc: 3.348735E-01
  mean_weight;FF_Inh;Input: 8.992811E-02
  mean_weight;Output;FB_Inh: 2.247386E+00
  mean_weight;Output;FF_Inh: 3.982895E-01
  mean_weight;Output;Input: 3.910722E-01
5c:
  mean_weight;FB_Exc;Output: 8.346867E-01
  mean_weight;FB_Inh;FB_Exc: 3.625602E-01
  mean_weight;FF_Inh;Input: 1.321021E-01
  mean_weight;Output;FB_Inh: 1.065949E-02
  # hit new upper bound
  mean_weight;Output;FF_Inh: 2.972505E+00
  mean_weight;Output;Input: 3.832324E-01
6:
  mean_weight;FB_Exc;FB_Exc: 7.165421E-01
  mean_weight;FB_Exc;Output: 1.731177E+00
  mean_weight;FB_Inh;FB_Exc: 5.844894E-02
  mean_weight;FF_Inh;Input: 1.979737E-01
  mean_weight;Output;FB_Exc: 8.671234E-02
  mean_weight;Output;FB_Inh: 1.511140E-02
  # hit new upper bound
  mean_weight;Output;FF_Inh: 2.983744E+00
  mean_weight;Output;Input: 2.396521E-01
6b:
  mean_weight;FB_Exc;FB_Exc: 5.125104E-02
  mean_weight;FB_Exc;FB_Inh: 1.670234E+00
  mean_weight;FB_Exc;Output: 4.941640E-01
  mean_weight;FB_Inh;FB_Exc: 1.795061E+00
  mean_weight;FF_Inh;Input: 5.600475E-01
  mean_weight;Output;FB_Exc: 1.130833E+00
  mean_weight;Output;FB_Inh: 1.265833E-01
  mean_weight;Output;FF_Inh: 1.405894E+00
  mean_weight;Output;Input: 3.062840E-01
